# Generated by Django 5.0.4 on 2024-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
